# Generated by Django 4.2.1 on 2023-05-09 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('responsavel', models.CharField(max_length=70)),
                ('situacao', models.CharField(choices=[('nova', 'nova'), ('em andamento', 'em andamento'), ('pendente', 'pendente'), ('resolvido', 'resolvido')])),
                ('nivel', models.PositiveIntegerField(choices=[(1, 1), (3, 3), (5, 5), (8, 8)], validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('prioridade', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)], validators=[django.core.validators.MinValueValidator(limit_value=1)])),
            ],
        ),
    ]
